/**
 * Server-only read/write access for the Document Vault's `vault_documents`
 * (supersedes `content-repository.ts`/`content_items` — see
 * `supabase/migrations/20261211090000_vault_documents.sql`).
 */

import "server-only";

import type { SupabaseClient } from "@supabase/supabase-js";

import type { VaultDocumentRow } from "@/lib/types/vault";

/* eslint-disable @typescript-eslint/no-explicit-any */
export type Db = SupabaseClient<any, any, any>;
/* eslint-enable @typescript-eslint/no-explicit-any */

export class VaultPersistenceError extends Error {
  constructor(
    readonly table: string,
    readonly operation: "select" | "insert" | "update" | "delete",
    cause: unknown,
  ) {
    const detail =
      cause && typeof cause === "object" && "message" in cause
        ? String((cause as { message: unknown }).message)
        : String(cause);
    super(`Vault: ${operation} on ${table} failed — ${detail}`);
    this.name = "VaultPersistenceError";
  }
}

export async function listVaultDocuments(client: Db, category?: string): Promise<VaultDocumentRow[]> {
  let query = client.from("vault_documents").select("*").order("created_at", { ascending: false });
  if (category) query = query.eq("category", category);
  const { data, error } = await query;
  if (error) throw new VaultPersistenceError("vault_documents", "select", error);
  return (data ?? []) as VaultDocumentRow[];
}

export async function getVaultDocument(client: Db, id: string): Promise<VaultDocumentRow | null> {
  const { data, error } = await client.from("vault_documents").select("*").eq("id", id).maybeSingle();
  if (error) throw new VaultPersistenceError("vault_documents", "select", error);
  return (data as VaultDocumentRow) ?? null;
}

export interface CreateVaultDocumentInput {
  /** Generated by the caller (not the database default) so the storage path can embed it before this row exists. */
  id: string;
  /**
   * Set explicitly rather than relying on `vault_documents.agency_id`'s
   * `default current_agency_id()` — an insert on the admin (service-role)
   * client has no session/JWT for that function to read, so the default
   * would silently resolve to null and trip the not-null constraint.
   */
  agencyId: string;
  category: string;
  title: string;
  storagePath: string;
  fileName: string;
  mimeType: string;
  fileSizeBytes: number;
  sourceDepartureGroupId?: string | null;
  uploadedByName: string;
}

export async function createVaultDocument(client: Db, input: CreateVaultDocumentInput): Promise<VaultDocumentRow> {
  const { data, error } = await client
    .from("vault_documents")
    .insert({
      id: input.id,
      agency_id: input.agencyId,
      category: input.category,
      title: input.title,
      storage_path: input.storagePath,
      file_name: input.fileName,
      mime_type: input.mimeType,
      file_size_bytes: input.fileSizeBytes,
      source_departure_group_id: input.sourceDepartureGroupId ?? null,
      uploaded_by_name: input.uploadedByName,
    })
    .select("*")
    .single();
  if (error) throw new VaultPersistenceError("vault_documents", "insert", error);
  return data as VaultDocumentRow;
}

export async function deleteVaultDocument(client: Db, id: string): Promise<void> {
  const { error } = await client.from("vault_documents").delete().eq("id", id);
  if (error) throw new VaultPersistenceError("vault_documents", "delete", error);
}
