-- Dynamic, admin-editable roles and permissions.
--
-- Replaces the fixed 7-role, code-defined capability matrices in
-- `lib/access/*.ts` with a database-backed model: `staff_roles` (any number
-- of roles per agency — the 7 existing ones become editable/deletable seed
-- rows, per the product decision) and `role_permissions` (one JSONB row per
-- role × module, holding exactly the same capability keys each module's
-- TypeScript interface already defines).
--
-- Enforcement stays application-layer only (`lib/access/*.ts` reads this
-- table instead of a hardcoded switch) — this migration deliberately does
-- NOT rewrite any of the ~50 existing RLS policies, which still key off the
-- literal role strings in `staff_profiles.role` / `agency_members.role`
-- (`current_staff_role()` is unchanged). That is what `base_role` is for:
-- every `staff_roles` row — including every custom one an Admin creates —
-- must declare which of the 7 RLS-recognised tiers its actual DATABASE
-- access rides on. A custom role's app-layer permissions (`role_permissions`)
-- can be MORE restrictive than that tier allows, never more permissive at
-- the raw row-security level. `staff_profiles.role` (text) is kept in sync
-- with the assigned role's `base_role` by a trigger, so nothing that reads
-- `current_staff_role()` today has to change.
--
-- `role_permissions.capabilities` for the 7 seed roles is seeded verbatim
-- from the live `capabilitiesFor*()` functions in lib/access/*.ts —
-- generated by a one-off script (not hand-transcribed), so nothing regresses
-- for any existing account the moment this migration lands: every seed row
-- reproduces exactly what that role could already do. Editing them from the
-- new Roles & Permissions screen is what makes them dynamic going forward.
--
-- Safe on a database with 20260808...20260923 applied.

-- ─────────────────────────────────────────────────────────────────────────────
-- A. staff_roles
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.staff_roles (
  id           uuid primary key default gen_random_uuid(),
  agency_id    uuid not null references public.agencies (id) on delete cascade default public.current_agency_id(),
  name         text not null,
  description  text,
  -- The RLS-recognised tier this role's actual database access rides on.
  -- Fixed set — intentionally NOT open to arbitrary custom values, because
  -- every existing RLS policy in this schema only knows these seven strings.
  base_role    text not null check (base_role in ('ADMIN','CEO','FINANCE','MARKETING','OPERATIONS','VISA','GUIDE')),
  -- True only for the 7 roles this migration seeds. Editable (name,
  -- description, permissions) like any other role — never deletable, so
  -- there is always at least one assignment target per base_role tier and a
  -- permissions fallback that can't be accidentally erased.
  is_system    boolean not null default false,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  unique (agency_id, name)
);

comment on table public.staff_roles is
  'Admin-editable roles, one row per role per agency. The 7 seeded system roles (is_system = true) are editable but not deletable. base_role is the RLS-recognised tier every role — including custom ones — must declare for database-level access; fine-grained capabilities live in role_permissions.';

create index if not exists staff_roles_agency_idx on public.staff_roles (agency_id);

drop trigger if exists staff_roles_set_updated_at on public.staff_roles;
create trigger staff_roles_set_updated_at
  before update on public.staff_roles
  for each row execute function public.set_updated_at();

-- ─────────────────────────────────────────────────────────────────────────────
-- B. role_permissions — one row per (role, module). `capabilities` holds
--    exactly the same keys the module's TypeScript Capabilities interface
--    defines (see lib/access/*.ts) — every flag that module already has,
--    CRUD or otherwise, not a generic create/read/update/delete subset. A
--    module absent from KNOWN_MODULES below cannot be inserted here at all.
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.role_permissions (
  id            uuid primary key default gen_random_uuid(),
  role_id       uuid not null references public.staff_roles (id) on delete cascade,
  module        text not null check (module in (
                   'departure_groups','documents','finance','leads','operations',
                   'packages','pilgrims','reports','settings','suppliers','visa',
                   'team','ai_agent','inbox'
                 )),
  capabilities  jsonb not null default '{}'::jsonb,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  unique (role_id, module)
);

comment on table public.role_permissions is
  'One JSONB capability row per (role, module). Keys mirror the module''s TypeScript Capabilities interface exactly — see lib/access/*.ts.';

create index if not exists role_permissions_role_idx on public.role_permissions (role_id);

drop trigger if exists role_permissions_set_updated_at on public.role_permissions;
create trigger role_permissions_set_updated_at
  before update on public.role_permissions
  for each row execute function public.set_updated_at();

-- ─────────────────────────────────────────────────────────────────────────────
-- C. staff_profiles.role_id / agency_members.role_id — the dynamic
--    assignment. `role` (text) stays as-is and keeps driving every existing
--    RLS policy; a trigger (section E) keeps it in sync with whichever
--    role_id is assigned, deriving from that role's base_role.
-- ─────────────────────────────────────────────────────────────────────────────
alter table public.staff_profiles add column if not exists role_id uuid references public.staff_roles (id);
alter table public.agency_members add column if not exists role_id uuid references public.staff_roles (id);

create index if not exists staff_profiles_role_id_idx on public.staff_profiles (role_id);
create index if not exists agency_members_role_id_idx on public.agency_members (role_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- D. Seed the 7 system roles, once per existing agency.
-- ─────────────────────────────────────────────────────────────────────────────
insert into public.staff_roles (agency_id, name, description, base_role, is_system)
select a.id, br.base_role, br.description, br.base_role, true
from public.agencies a
cross join (values
  ('ADMIN',      'Full administrative access.'),
  ('CEO',        'Business visibility, read-only.'),
  ('FINANCE',    'Finance operations.'),
  ('MARKETING',  'Marketing operations.'),
  ('OPERATIONS', 'Day-to-day operations.'),
  ('VISA',       'Visa processing.'),
  ('GUIDE',      'Field guide — assigned groups only.')
) as br(base_role, description)
on conflict (agency_id, name) do nothing;

-- ─────────────────────────────────────────────────────────────────────────────
-- E. Backfill staff_profiles.role_id / agency_members.role_id from the
--    existing text role, and the trigger that keeps `role` (text) in sync
--    with `role_id` going forward — the mechanism that lets RLS stay
--    completely unchanged while permissions become dynamic.
-- ─────────────────────────────────────────────────────────────────────────────
update public.staff_profiles sp
set role_id = sr.id
from public.staff_roles sr
where sr.agency_id = sp.agency_id and sr.base_role = sp.role and sr.is_system = true and sp.role_id is null;

update public.agency_members am
set role_id = sr.id
from public.staff_roles sr
where sr.agency_id = am.agency_id and sr.base_role = am.role and sr.is_system = true and am.role_id is null;

create or replace function public.sync_staff_profile_role_text() returns trigger
  language plpgsql security definer set search_path = public as $$
declare
  v_base_role text;
begin
  if new.role_id is distinct from old.role_id and new.role_id is not null then
    select base_role into v_base_role from public.staff_roles where id = new.role_id;
    if v_base_role is not null then
      new.role := v_base_role;
    end if;
  end if;
  return new;
end;
$$;

comment on function public.sync_staff_profile_role_text() is
  'Keeps staff_profiles.role (the literal text every RLS policy reads) in sync with whichever staff_roles.base_role the assigned role_id maps to. Runs BEFORE UPDATE so staff_profiles_sync_agency_membership (20260923090000, AFTER UPDATE) mirrors the already-correct value onto agency_members.';

drop trigger if exists staff_profiles_sync_role_text on public.staff_profiles;
create trigger staff_profiles_sync_role_text
  before update on public.staff_profiles
  for each row execute function public.sync_staff_profile_role_text();

-- Same sync for agency_members.role, so switch_active_agency() (which reads
-- agency_members.role, not staff_profiles.role) also stays correct once a
-- membership's role_id changes.
create or replace function public.sync_agency_member_role_text() returns trigger
  language plpgsql security definer set search_path = public as $$
declare
  v_base_role text;
begin
  if new.role_id is distinct from old.role_id and new.role_id is not null then
    select base_role into v_base_role from public.staff_roles where id = new.role_id;
    if v_base_role is not null then
      new.role := v_base_role;
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists agency_members_sync_role_text on public.agency_members;
create trigger agency_members_sync_role_text
  before update on public.agency_members
  for each row execute function public.sync_agency_member_role_text();

-- ─────────────────────────────────────────────────────────────────────────────
-- F. Row Level Security. Coarse and consistent with every other tenant
--    table: read by anyone signed into the agency (every role needs to see
--    role names to render the Team list / pickers), write by Admin only.
--    system-role protection (no delete, base_role/is_system immutable after
--    creation) is enforced in the application layer's Server Actions, not
--    here — same posture as every other business-rule check in this schema
--    that isn't a tenant boundary.
-- ─────────────────────────────────────────────────────────────────────────────
alter table public.staff_roles enable row level security;
alter table public.role_permissions enable row level security;

drop policy if exists staff_roles_select on public.staff_roles;
create policy staff_roles_select on public.staff_roles
  for select to authenticated
  using (agency_id = public.current_agency_id());

drop policy if exists staff_roles_write on public.staff_roles;
create policy staff_roles_write on public.staff_roles
  for all to authenticated
  using (agency_id = public.current_agency_id() and public.current_staff_role() = 'ADMIN')
  with check (agency_id = public.current_agency_id() and public.current_staff_role() = 'ADMIN');

drop policy if exists role_permissions_select on public.role_permissions;
create policy role_permissions_select on public.role_permissions
  for select to authenticated
  using (exists (select 1 from public.staff_roles r where r.id = role_permissions.role_id and r.agency_id = public.current_agency_id()));

drop policy if exists role_permissions_write on public.role_permissions;
create policy role_permissions_write on public.role_permissions
  for all to authenticated
  using (
    public.current_staff_role() = 'ADMIN'
    and exists (select 1 from public.staff_roles r where r.id = role_permissions.role_id and r.agency_id = public.current_agency_id())
  )
  with check (
    public.current_staff_role() = 'ADMIN'
    and exists (select 1 from public.staff_roles r where r.id = role_permissions.role_id and r.agency_id = public.current_agency_id())
  );

-- ─────────────────────────────────────────────────────────────────────────────
-- G. Seed role_permissions for the 7 system roles from the live
--    lib/access/*.ts capability functions — generated, not hand-transcribed.
-- ─────────────────────────────────────────────────────────────────────────────
insert into public.role_permissions (role_id, module, capabilities)
select r.id, v.module, v.capabilities::jsonb
from public.staff_roles r
join (values
  ('ADMIN', 'departure_groups', '{"viewModule":true,"createGroup":true,"editGroupDetails":true,"cancelOrArchiveGroup":true,"overrideCapacityAndPrice":true,"manageFlights":true,"manageAccommodation":true,"manageTransport":true,"manageRooming":true,"unlockRoomAssignments":true,"manageReadiness":true,"manageTasks":true,"manageDocumentsAndVisa":true,"addBookings":true,"viewFinance":true,"recordPayments":true,"viewSupplierCosts":true,"viewSensitiveTravellerData":true,"sendGroupCommunications":true,"exportReports":true,"restrictedToAssignedGroups":false,"manageTravellerCustomisations":true,"approveDiscounts":true,"viewPilgrimPricing":true}'::jsonb),
  ('ADMIN', 'documents', '{"viewModule":true,"viewDocumentFile":true,"uploadOnBehalf":true,"verifyDocuments":true,"requestRework":true,"waiveRequirement":true,"assignReviewer":true,"sendReminders":true,"runAiScan":true,"viewAiFindings":true,"overrideAiFinding":true,"manageAgentSettings":true,"bulkActions":true,"exportChecklist":true,"exportVisaPack":true,"downloadVerifiedFiles":true,"readOnly":false,"scopedToPaymentProof":false}'::jsonb),
  ('ADMIN', 'finance', '{"viewModule":true,"viewReceivables":true,"viewLedger":true,"viewInvoices":true,"viewSupplierPayables":true,"viewRefunds":true,"viewReconciliation":true,"recordPayments":true,"verifyPayments":true,"reversePayments":true,"createInvoices":true,"sendInvoices":true,"voidInvoices":true,"recordSupplierPayments":true,"requestRefunds":true,"approveRefunds":true,"applyAdjustments":true,"approveAdjustments":true,"changeMilestoneDueDates":true,"assignFinanceOwner":true,"sendReminders":true,"exportFinanceReport":true,"viewPaymentStatusOnly":false,"readOnly":false}'::jsonb),
  ('ADMIN', 'leads', '{"viewModule":true,"createLead":true,"editLead":true,"changeStage":true,"assignLeads":true,"logContact":true,"addNote":true,"sendQuote":true,"findGroups":true,"convertToBooking":true,"mergeDuplicates":true,"deleteLead":true,"manageSourcesAndAutomation":true,"viewPipelineValue":true,"viewAnalytics":true,"viewAllOwners":true,"convertedOnly":false}'::jsonb),
  ('ADMIN', 'operations', '{"viewModule":true,"createTask":true,"editTask":true,"reassignTask":true,"bulkUpdateTasks":true,"completeTask":true,"viewSupplierBoard":true,"requestSupplier":true,"confirmSupplier":true,"addSupplierBooking":true,"manageFlights":true,"manageAccommodation":true,"manageRooming":true,"manageTransport":true,"assignGuide":true,"generateRunSheet":true,"exportManifest":true,"viewReadinessMatrix":true,"viewSupplierCosts":true,"viewFinanceBlockers":true,"viewPilgrimContactDetails":true,"exportOperationsReport":true,"readOnly":false,"assignedGroupOnly":false}'::jsonb),
  ('ADMIN', 'packages', '{"viewModule":true,"createPackage":true,"editPackage":true,"editPricing":true,"publishPackage":true,"duplicatePackage":true,"archiveOrRestorePackage":true,"deletePackage":true,"toggleFeatured":true,"viewInternalFinance":true,"exportCatalogue":true,"createGroupFromPackage":true}'::jsonb),
  ('ADMIN', 'pilgrims', '{"viewModule":true,"createPilgrim":true,"editPersonalDetails":true,"viewPassportAndIdentity":true,"viewDocuments":true,"uploadDocuments":true,"verifyDocuments":true,"manageVisa":true,"viewPayments":true,"recordPayments":true,"manageTravelAndRooming":true,"viewMedical":true,"editMedical":true,"manageSupportRequests":true,"viewEmergencyContact":true,"sendCommunications":true,"moveOrCancelPilgrim":true,"managePortalAccess":true,"exportPilgrims":true,"assignedGroupOnly":false}'::jsonb),
  ('ADMIN', 'reports', '{"viewModule":true,"viewOverview":true,"viewSales":true,"viewFinance":true,"viewGroups":true,"viewPilgrims":true,"viewSuppliers":true,"viewSaved":true,"viewCostAndMargin":true,"viewAllBranches":true,"ownGroupsOnly":false,"createCustomReports":true,"saveReports":true,"shareSavedReports":true,"scheduleReports":true,"exportCsv":true,"exportExcel":true,"exportPdf":true}'::jsonb),
  ('ADMIN', 'settings', '{"viewModule":true,"viewOrganisation":true,"editOrganisation":true,"viewBranches":true,"editBranches":true,"viewBranding":true,"editBranding":true,"viewOperations":true,"editOperations":true,"viewCommunications":true,"editCommunications":true,"communicationsScopedToOwnRole":false,"viewFinance":true,"editFinance":true,"viewIntegrations":true,"editIntegrations":true,"viewSecurity":true,"editSecurity":true,"viewAuditLog":true,"editData":true,"exportData":true,"importData":true,"viewDangerZone":true}'::jsonb),
  ('ADMIN', 'suppliers', '{"viewModule":true,"createSupplier":true,"editSupplier":true,"deactivateSupplier":true,"setReliability":true,"viewContacts":true,"viewEmergencyContactsOnly":false,"manageContacts":true,"viewCommitments":true,"createCommitment":true,"requestCommitment":true,"confirmCommitment":true,"uploadEvidence":true,"disputeCommitment":true,"viewCosts":true,"viewPayments":true,"recordPayment":true,"viewInternalNotes":true,"importExport":true,"readOnly":false,"assignedGroupOnly":false}'::jsonb),
  ('ADMIN', 'visa', '{"viewModule":true,"viewApplicationDetail":true,"viewVisaNumberAndFile":true,"viewFullPassportNumber":true,"createBatch":true,"manageBatch":true,"markSubmitted":true,"recordStatusCheck":true,"recordIssuedVisa":true,"verifyIssuedVisa":true,"amendIssuedVisa":true,"recordRejection":true,"requestRework":true,"assignOfficer":true,"uploadVisaEvidence":true,"sendReminders":true,"runAiAssistant":true,"exportSubmissionPack":true,"exportRiskReport":true,"viewGroupRiskBoard":true,"viewPaymentBlockersOnly":false,"readOnly":false,"assignedGroupOnly":false,"configureThresholds":true}'::jsonb),
  ('ADMIN', 'team', '{"viewModule":true,"viewFullDirectory":true,"inviteStaff":true,"editProfile":true,"changeRole":true,"deactivateStaff":true,"assignGroups":true,"viewWorkload":true,"viewSecurityTab":true,"manageSessionsAndPasswords":true,"exportTeamList":true,"exportAccessAudit":true,"viewOwnProfileOnly":false}'::jsonb),
  ('ADMIN', 'ai_agent', '{"viewModule":true,"editSettings":true,"manageKnowledgeBase":true,"viewAnalytics":true}'::jsonb),
  ('ADMIN', 'inbox', '{"viewModule":true,"takeControl":true,"releaseToAi":true,"sendMessage":true,"closeConversation":true,"assignConversation":true,"retryFailedJob":true}'::jsonb),
  ('CEO', 'departure_groups', '{"viewModule":true,"createGroup":false,"editGroupDetails":false,"cancelOrArchiveGroup":false,"overrideCapacityAndPrice":false,"manageFlights":false,"manageAccommodation":false,"manageTransport":false,"manageRooming":false,"unlockRoomAssignments":false,"manageReadiness":false,"manageTasks":true,"manageDocumentsAndVisa":false,"addBookings":false,"viewFinance":true,"recordPayments":false,"viewSupplierCosts":true,"viewSensitiveTravellerData":true,"sendGroupCommunications":false,"exportReports":true,"restrictedToAssignedGroups":false,"manageTravellerCustomisations":false,"approveDiscounts":false,"viewPilgrimPricing":true}'::jsonb),
  ('CEO', 'documents', '{"viewModule":true,"viewDocumentFile":false,"uploadOnBehalf":false,"verifyDocuments":false,"requestRework":false,"waiveRequirement":false,"assignReviewer":false,"sendReminders":false,"runAiScan":false,"viewAiFindings":true,"overrideAiFinding":false,"manageAgentSettings":false,"bulkActions":false,"exportChecklist":true,"exportVisaPack":false,"downloadVerifiedFiles":false,"readOnly":true,"scopedToPaymentProof":false}'::jsonb),
  ('CEO', 'finance', '{"viewModule":true,"viewReceivables":true,"viewLedger":true,"viewInvoices":true,"viewSupplierPayables":true,"viewRefunds":true,"viewReconciliation":true,"recordPayments":false,"verifyPayments":false,"reversePayments":false,"createInvoices":false,"sendInvoices":false,"voidInvoices":false,"recordSupplierPayments":false,"requestRefunds":false,"approveRefunds":false,"applyAdjustments":false,"approveAdjustments":false,"changeMilestoneDueDates":false,"assignFinanceOwner":false,"sendReminders":false,"exportFinanceReport":true,"viewPaymentStatusOnly":false,"readOnly":true}'::jsonb),
  ('CEO', 'leads', '{"viewModule":true,"createLead":false,"editLead":false,"changeStage":false,"assignLeads":false,"logContact":false,"addNote":false,"sendQuote":false,"findGroups":false,"convertToBooking":false,"mergeDuplicates":false,"deleteLead":false,"manageSourcesAndAutomation":false,"viewPipelineValue":true,"viewAnalytics":true,"viewAllOwners":true,"convertedOnly":false}'::jsonb),
  ('CEO', 'operations', '{"viewModule":true,"createTask":true,"editTask":false,"reassignTask":false,"bulkUpdateTasks":false,"completeTask":false,"viewSupplierBoard":true,"requestSupplier":false,"confirmSupplier":false,"addSupplierBooking":false,"manageFlights":false,"manageAccommodation":false,"manageRooming":false,"manageTransport":false,"assignGuide":false,"generateRunSheet":false,"exportManifest":false,"viewReadinessMatrix":true,"viewSupplierCosts":true,"viewFinanceBlockers":true,"viewPilgrimContactDetails":true,"exportOperationsReport":true,"readOnly":true,"assignedGroupOnly":false}'::jsonb),
  ('CEO', 'packages', '{"viewModule":true,"createPackage":false,"editPackage":false,"editPricing":false,"publishPackage":false,"duplicatePackage":false,"archiveOrRestorePackage":false,"deletePackage":false,"toggleFeatured":false,"viewInternalFinance":true,"exportCatalogue":true,"createGroupFromPackage":false}'::jsonb),
  ('CEO', 'pilgrims', '{"viewModule":true,"createPilgrim":false,"editPersonalDetails":false,"viewPassportAndIdentity":true,"viewDocuments":true,"uploadDocuments":false,"verifyDocuments":false,"manageVisa":false,"viewPayments":true,"recordPayments":false,"manageTravelAndRooming":false,"viewMedical":false,"editMedical":false,"manageSupportRequests":false,"viewEmergencyContact":true,"sendCommunications":false,"moveOrCancelPilgrim":false,"managePortalAccess":false,"exportPilgrims":true,"assignedGroupOnly":false}'::jsonb),
  ('CEO', 'reports', '{"viewModule":true,"viewOverview":true,"viewSales":true,"viewFinance":true,"viewGroups":true,"viewPilgrims":true,"viewSuppliers":true,"viewSaved":true,"viewCostAndMargin":true,"viewAllBranches":true,"ownGroupsOnly":false,"createCustomReports":false,"saveReports":true,"shareSavedReports":true,"scheduleReports":true,"exportCsv":true,"exportExcel":true,"exportPdf":true}'::jsonb),
  ('CEO', 'settings', '{"viewModule":true,"viewOrganisation":true,"editOrganisation":false,"viewBranches":true,"editBranches":false,"viewBranding":true,"editBranding":false,"viewOperations":false,"editOperations":false,"viewCommunications":false,"editCommunications":false,"communicationsScopedToOwnRole":false,"viewFinance":false,"editFinance":false,"viewIntegrations":false,"editIntegrations":false,"viewSecurity":false,"editSecurity":false,"viewAuditLog":true,"editData":false,"exportData":true,"importData":false,"viewDangerZone":false}'::jsonb),
  ('CEO', 'suppliers', '{"viewModule":true,"createSupplier":false,"editSupplier":false,"deactivateSupplier":false,"setReliability":false,"viewContacts":true,"viewEmergencyContactsOnly":false,"manageContacts":false,"viewCommitments":true,"createCommitment":false,"requestCommitment":false,"confirmCommitment":false,"uploadEvidence":false,"disputeCommitment":false,"viewCosts":true,"viewPayments":true,"recordPayment":false,"viewInternalNotes":true,"importExport":true,"readOnly":true,"assignedGroupOnly":false}'::jsonb),
  ('CEO', 'visa', '{"viewModule":true,"viewApplicationDetail":true,"viewVisaNumberAndFile":true,"viewFullPassportNumber":true,"createBatch":false,"manageBatch":false,"markSubmitted":false,"recordStatusCheck":false,"recordIssuedVisa":false,"verifyIssuedVisa":false,"amendIssuedVisa":false,"recordRejection":false,"requestRework":false,"assignOfficer":false,"uploadVisaEvidence":false,"sendReminders":false,"runAiAssistant":true,"exportSubmissionPack":false,"exportRiskReport":true,"viewGroupRiskBoard":true,"viewPaymentBlockersOnly":false,"readOnly":true,"assignedGroupOnly":false,"configureThresholds":false}'::jsonb),
  ('CEO', 'team', '{"viewModule":true,"viewFullDirectory":true,"inviteStaff":false,"editProfile":false,"changeRole":false,"deactivateStaff":false,"assignGroups":false,"viewWorkload":true,"viewSecurityTab":false,"manageSessionsAndPasswords":false,"exportTeamList":true,"exportAccessAudit":false,"viewOwnProfileOnly":false}'::jsonb),
  ('CEO', 'ai_agent', '{"viewModule":true,"editSettings":false,"manageKnowledgeBase":false,"viewAnalytics":true}'::jsonb),
  ('CEO', 'inbox', '{"viewModule":true,"takeControl":false,"releaseToAi":false,"sendMessage":false,"closeConversation":false,"assignConversation":false,"retryFailedJob":false}'::jsonb),
  ('FINANCE', 'departure_groups', '{"viewModule":true,"createGroup":false,"editGroupDetails":false,"cancelOrArchiveGroup":false,"overrideCapacityAndPrice":false,"manageFlights":false,"manageAccommodation":false,"manageTransport":false,"manageRooming":false,"unlockRoomAssignments":false,"manageReadiness":true,"manageTasks":true,"manageDocumentsAndVisa":false,"addBookings":false,"viewFinance":true,"recordPayments":true,"viewSupplierCosts":true,"viewSensitiveTravellerData":false,"sendGroupCommunications":false,"exportReports":true,"restrictedToAssignedGroups":false,"manageTravellerCustomisations":false,"approveDiscounts":true,"viewPilgrimPricing":true}'::jsonb),
  ('FINANCE', 'documents', '{"viewModule":true,"viewDocumentFile":true,"uploadOnBehalf":true,"verifyDocuments":true,"requestRework":true,"waiveRequirement":false,"assignReviewer":false,"sendReminders":true,"runAiScan":false,"viewAiFindings":false,"overrideAiFinding":false,"manageAgentSettings":false,"bulkActions":false,"exportChecklist":true,"exportVisaPack":false,"downloadVerifiedFiles":false,"readOnly":false,"scopedToPaymentProof":true}'::jsonb),
  ('FINANCE', 'finance', '{"viewModule":true,"viewReceivables":true,"viewLedger":true,"viewInvoices":true,"viewSupplierPayables":true,"viewRefunds":true,"viewReconciliation":true,"recordPayments":true,"verifyPayments":true,"reversePayments":true,"createInvoices":true,"sendInvoices":true,"voidInvoices":true,"recordSupplierPayments":true,"requestRefunds":true,"approveRefunds":false,"applyAdjustments":true,"approveAdjustments":false,"changeMilestoneDueDates":true,"assignFinanceOwner":true,"sendReminders":true,"exportFinanceReport":true,"viewPaymentStatusOnly":false,"readOnly":false}'::jsonb),
  ('FINANCE', 'leads', '{"viewModule":true,"createLead":false,"editLead":false,"changeStage":false,"assignLeads":false,"logContact":false,"addNote":false,"sendQuote":false,"findGroups":false,"convertToBooking":false,"mergeDuplicates":false,"deleteLead":false,"manageSourcesAndAutomation":false,"viewPipelineValue":true,"viewAnalytics":true,"viewAllOwners":true,"convertedOnly":true}'::jsonb),
  ('FINANCE', 'operations', '{"viewModule":true,"createTask":false,"editTask":false,"reassignTask":false,"bulkUpdateTasks":false,"completeTask":false,"viewSupplierBoard":true,"requestSupplier":false,"confirmSupplier":false,"addSupplierBooking":false,"manageFlights":false,"manageAccommodation":false,"manageRooming":false,"manageTransport":false,"assignGuide":false,"generateRunSheet":false,"exportManifest":false,"viewReadinessMatrix":true,"viewSupplierCosts":true,"viewFinanceBlockers":true,"viewPilgrimContactDetails":false,"exportOperationsReport":false,"readOnly":true,"assignedGroupOnly":false}'::jsonb),
  ('FINANCE', 'packages', '{"viewModule":true,"createPackage":false,"editPackage":false,"editPricing":true,"publishPackage":false,"duplicatePackage":false,"archiveOrRestorePackage":false,"deletePackage":false,"toggleFeatured":false,"viewInternalFinance":true,"exportCatalogue":true,"createGroupFromPackage":false}'::jsonb),
  ('FINANCE', 'pilgrims', '{"viewModule":true,"createPilgrim":false,"editPersonalDetails":false,"viewPassportAndIdentity":false,"viewDocuments":false,"uploadDocuments":false,"verifyDocuments":false,"manageVisa":false,"viewPayments":true,"recordPayments":true,"manageTravelAndRooming":false,"viewMedical":false,"editMedical":false,"manageSupportRequests":false,"viewEmergencyContact":false,"sendCommunications":false,"moveOrCancelPilgrim":false,"managePortalAccess":false,"exportPilgrims":true,"assignedGroupOnly":false}'::jsonb),
  ('FINANCE', 'reports', '{"viewModule":true,"viewOverview":true,"viewSales":false,"viewFinance":true,"viewGroups":true,"viewPilgrims":false,"viewSuppliers":false,"viewSaved":true,"viewCostAndMargin":true,"viewAllBranches":false,"ownGroupsOnly":false,"createCustomReports":false,"saveReports":true,"shareSavedReports":false,"scheduleReports":false,"exportCsv":true,"exportExcel":true,"exportPdf":false}'::jsonb),
  ('FINANCE', 'settings', '{"viewModule":true,"viewOrganisation":false,"editOrganisation":false,"viewBranches":false,"editBranches":false,"viewBranding":false,"editBranding":false,"viewOperations":false,"editOperations":false,"viewCommunications":false,"editCommunications":false,"communicationsScopedToOwnRole":false,"viewFinance":true,"editFinance":true,"viewIntegrations":false,"editIntegrations":false,"viewSecurity":false,"editSecurity":false,"viewAuditLog":false,"editData":false,"exportData":false,"importData":false,"viewDangerZone":false}'::jsonb),
  ('FINANCE', 'suppliers', '{"viewModule":true,"createSupplier":false,"editSupplier":false,"deactivateSupplier":false,"setReliability":false,"viewContacts":true,"viewEmergencyContactsOnly":false,"manageContacts":false,"viewCommitments":true,"createCommitment":false,"requestCommitment":false,"confirmCommitment":false,"uploadEvidence":false,"disputeCommitment":false,"viewCosts":true,"viewPayments":true,"recordPayment":true,"viewInternalNotes":false,"importExport":false,"readOnly":true,"assignedGroupOnly":false}'::jsonb),
  ('FINANCE', 'visa', '{"viewModule":true,"viewApplicationDetail":false,"viewVisaNumberAndFile":false,"viewFullPassportNumber":false,"createBatch":false,"manageBatch":false,"markSubmitted":false,"recordStatusCheck":false,"recordIssuedVisa":false,"verifyIssuedVisa":false,"amendIssuedVisa":false,"recordRejection":false,"requestRework":false,"assignOfficer":false,"uploadVisaEvidence":false,"sendReminders":false,"runAiAssistant":false,"exportSubmissionPack":false,"exportRiskReport":false,"viewGroupRiskBoard":false,"viewPaymentBlockersOnly":true,"readOnly":true,"assignedGroupOnly":false,"configureThresholds":false}'::jsonb),
  ('FINANCE', 'team', '{"viewModule":false,"viewFullDirectory":false,"inviteStaff":false,"editProfile":false,"changeRole":false,"deactivateStaff":false,"assignGroups":false,"viewWorkload":false,"viewSecurityTab":false,"manageSessionsAndPasswords":false,"exportTeamList":false,"exportAccessAudit":false,"viewOwnProfileOnly":true}'::jsonb),
  ('FINANCE', 'ai_agent', '{"viewModule":false,"editSettings":false,"manageKnowledgeBase":false,"viewAnalytics":false}'::jsonb),
  ('FINANCE', 'inbox', '{"viewModule":true,"takeControl":false,"releaseToAi":false,"sendMessage":false,"closeConversation":false,"assignConversation":false,"retryFailedJob":false}'::jsonb),
  ('MARKETING', 'departure_groups', '{"viewModule":true,"createGroup":false,"editGroupDetails":false,"cancelOrArchiveGroup":false,"overrideCapacityAndPrice":false,"manageFlights":false,"manageAccommodation":false,"manageTransport":false,"manageRooming":false,"unlockRoomAssignments":false,"manageReadiness":false,"manageTasks":false,"manageDocumentsAndVisa":false,"addBookings":true,"viewFinance":false,"recordPayments":false,"viewSupplierCosts":false,"viewSensitiveTravellerData":false,"sendGroupCommunications":true,"exportReports":false,"restrictedToAssignedGroups":false,"manageTravellerCustomisations":true,"approveDiscounts":false,"viewPilgrimPricing":true}'::jsonb),
  ('MARKETING', 'documents', '{"viewModule":true,"viewDocumentFile":false,"uploadOnBehalf":false,"verifyDocuments":false,"requestRework":false,"waiveRequirement":false,"assignReviewer":false,"sendReminders":true,"runAiScan":false,"viewAiFindings":false,"overrideAiFinding":false,"manageAgentSettings":false,"bulkActions":false,"exportChecklist":false,"exportVisaPack":false,"downloadVerifiedFiles":false,"readOnly":false,"scopedToPaymentProof":false}'::jsonb),
  ('MARKETING', 'finance', '{"viewModule":true,"viewReceivables":true,"viewLedger":false,"viewInvoices":false,"viewSupplierPayables":false,"viewRefunds":false,"viewReconciliation":false,"recordPayments":false,"verifyPayments":false,"reversePayments":false,"createInvoices":false,"sendInvoices":false,"voidInvoices":false,"recordSupplierPayments":false,"requestRefunds":false,"approveRefunds":false,"applyAdjustments":false,"approveAdjustments":false,"changeMilestoneDueDates":false,"assignFinanceOwner":false,"sendReminders":false,"exportFinanceReport":false,"viewPaymentStatusOnly":true,"readOnly":false}'::jsonb),
  ('MARKETING', 'leads', '{"viewModule":true,"createLead":true,"editLead":true,"changeStage":true,"assignLeads":true,"logContact":true,"addNote":true,"sendQuote":true,"findGroups":true,"convertToBooking":true,"mergeDuplicates":false,"deleteLead":false,"manageSourcesAndAutomation":false,"viewPipelineValue":true,"viewAnalytics":true,"viewAllOwners":true,"convertedOnly":false}'::jsonb),
  ('MARKETING', 'operations', '{"viewModule":true,"createTask":false,"editTask":false,"reassignTask":false,"bulkUpdateTasks":false,"completeTask":false,"viewSupplierBoard":false,"requestSupplier":false,"confirmSupplier":false,"addSupplierBooking":false,"manageFlights":false,"manageAccommodation":false,"manageRooming":false,"manageTransport":false,"assignGuide":false,"generateRunSheet":false,"exportManifest":false,"viewReadinessMatrix":true,"viewSupplierCosts":false,"viewFinanceBlockers":false,"viewPilgrimContactDetails":false,"exportOperationsReport":false,"readOnly":true,"assignedGroupOnly":false}'::jsonb),
  ('MARKETING', 'packages', '{"viewModule":true,"createPackage":false,"editPackage":false,"editPricing":false,"publishPackage":false,"duplicatePackage":true,"archiveOrRestorePackage":false,"deletePackage":false,"toggleFeatured":true,"viewInternalFinance":false,"exportCatalogue":false,"createGroupFromPackage":false}'::jsonb),
  ('MARKETING', 'pilgrims', '{"viewModule":true,"createPilgrim":false,"editPersonalDetails":true,"viewPassportAndIdentity":false,"viewDocuments":false,"uploadDocuments":false,"verifyDocuments":false,"manageVisa":false,"viewPayments":false,"recordPayments":false,"manageTravelAndRooming":false,"viewMedical":false,"editMedical":false,"manageSupportRequests":false,"viewEmergencyContact":false,"sendCommunications":true,"moveOrCancelPilgrim":false,"managePortalAccess":false,"exportPilgrims":false,"assignedGroupOnly":false}'::jsonb),
  ('MARKETING', 'reports', '{"viewModule":true,"viewOverview":true,"viewSales":true,"viewFinance":false,"viewGroups":false,"viewPilgrims":false,"viewSuppliers":false,"viewSaved":true,"viewCostAndMargin":false,"viewAllBranches":false,"ownGroupsOnly":false,"createCustomReports":false,"saveReports":true,"shareSavedReports":false,"scheduleReports":false,"exportCsv":true,"exportExcel":false,"exportPdf":false}'::jsonb),
  ('MARKETING', 'settings', '{"viewModule":true,"viewOrganisation":false,"editOrganisation":false,"viewBranches":false,"editBranches":false,"viewBranding":false,"editBranding":false,"viewOperations":false,"editOperations":false,"viewCommunications":true,"editCommunications":true,"communicationsScopedToOwnRole":true,"viewFinance":false,"editFinance":false,"viewIntegrations":false,"editIntegrations":false,"viewSecurity":false,"editSecurity":false,"viewAuditLog":false,"editData":false,"exportData":false,"importData":false,"viewDangerZone":false}'::jsonb),
  ('MARKETING', 'suppliers', '{"viewModule":false,"createSupplier":false,"editSupplier":false,"deactivateSupplier":false,"setReliability":false,"viewContacts":false,"viewEmergencyContactsOnly":false,"manageContacts":false,"viewCommitments":false,"createCommitment":false,"requestCommitment":false,"confirmCommitment":false,"uploadEvidence":false,"disputeCommitment":false,"viewCosts":false,"viewPayments":false,"recordPayment":false,"viewInternalNotes":false,"importExport":false,"readOnly":false,"assignedGroupOnly":false}'::jsonb),
  ('MARKETING', 'visa', '{"viewModule":true,"viewApplicationDetail":false,"viewVisaNumberAndFile":false,"viewFullPassportNumber":false,"createBatch":false,"manageBatch":false,"markSubmitted":false,"recordStatusCheck":false,"recordIssuedVisa":false,"verifyIssuedVisa":false,"amendIssuedVisa":false,"recordRejection":false,"requestRework":false,"assignOfficer":false,"uploadVisaEvidence":false,"sendReminders":true,"runAiAssistant":false,"exportSubmissionPack":false,"exportRiskReport":false,"viewGroupRiskBoard":false,"viewPaymentBlockersOnly":false,"readOnly":true,"assignedGroupOnly":false,"configureThresholds":false}'::jsonb),
  ('MARKETING', 'team', '{"viewModule":false,"viewFullDirectory":false,"inviteStaff":false,"editProfile":false,"changeRole":false,"deactivateStaff":false,"assignGroups":false,"viewWorkload":false,"viewSecurityTab":false,"manageSessionsAndPasswords":false,"exportTeamList":false,"exportAccessAudit":false,"viewOwnProfileOnly":true}'::jsonb),
  ('MARKETING', 'ai_agent', '{"viewModule":true,"editSettings":false,"manageKnowledgeBase":false,"viewAnalytics":true}'::jsonb),
  ('MARKETING', 'inbox', '{"viewModule":true,"takeControl":true,"releaseToAi":true,"sendMessage":true,"closeConversation":true,"assignConversation":true,"retryFailedJob":false}'::jsonb),
  ('OPERATIONS', 'departure_groups', '{"viewModule":true,"createGroup":true,"editGroupDetails":true,"cancelOrArchiveGroup":false,"overrideCapacityAndPrice":false,"manageFlights":true,"manageAccommodation":true,"manageTransport":true,"manageRooming":true,"unlockRoomAssignments":false,"manageReadiness":true,"manageTasks":true,"manageDocumentsAndVisa":true,"addBookings":true,"viewFinance":false,"recordPayments":false,"viewSupplierCosts":true,"viewSensitiveTravellerData":true,"sendGroupCommunications":true,"exportReports":true,"restrictedToAssignedGroups":false,"manageTravellerCustomisations":true,"approveDiscounts":false,"viewPilgrimPricing":true}'::jsonb),
  ('OPERATIONS', 'documents', '{"viewModule":true,"viewDocumentFile":true,"uploadOnBehalf":true,"verifyDocuments":true,"requestRework":true,"waiveRequirement":true,"assignReviewer":true,"sendReminders":true,"runAiScan":true,"viewAiFindings":true,"overrideAiFinding":true,"manageAgentSettings":true,"bulkActions":true,"exportChecklist":true,"exportVisaPack":true,"downloadVerifiedFiles":true,"readOnly":false,"scopedToPaymentProof":false}'::jsonb),
  ('OPERATIONS', 'finance', '{"viewModule":true,"viewReceivables":true,"viewLedger":false,"viewInvoices":false,"viewSupplierPayables":false,"viewRefunds":false,"viewReconciliation":false,"recordPayments":false,"verifyPayments":false,"reversePayments":false,"createInvoices":false,"sendInvoices":false,"voidInvoices":false,"recordSupplierPayments":false,"requestRefunds":false,"approveRefunds":false,"applyAdjustments":false,"approveAdjustments":false,"changeMilestoneDueDates":false,"assignFinanceOwner":false,"sendReminders":false,"exportFinanceReport":false,"viewPaymentStatusOnly":true,"readOnly":false}'::jsonb),
  ('OPERATIONS', 'leads', '{"viewModule":true,"createLead":false,"editLead":false,"changeStage":false,"assignLeads":false,"logContact":false,"addNote":false,"sendQuote":false,"findGroups":false,"convertToBooking":false,"mergeDuplicates":false,"deleteLead":false,"manageSourcesAndAutomation":false,"viewPipelineValue":false,"viewAnalytics":false,"viewAllOwners":true,"convertedOnly":true}'::jsonb),
  ('OPERATIONS', 'operations', '{"viewModule":true,"createTask":true,"editTask":true,"reassignTask":true,"bulkUpdateTasks":true,"completeTask":true,"viewSupplierBoard":true,"requestSupplier":true,"confirmSupplier":true,"addSupplierBooking":true,"manageFlights":true,"manageAccommodation":true,"manageRooming":true,"manageTransport":true,"assignGuide":true,"generateRunSheet":true,"exportManifest":true,"viewReadinessMatrix":true,"viewSupplierCosts":true,"viewFinanceBlockers":true,"viewPilgrimContactDetails":true,"exportOperationsReport":true,"readOnly":false,"assignedGroupOnly":false}'::jsonb),
  ('OPERATIONS', 'packages', '{"viewModule":true,"createPackage":true,"editPackage":true,"editPricing":true,"publishPackage":true,"duplicatePackage":true,"archiveOrRestorePackage":true,"deletePackage":false,"toggleFeatured":true,"viewInternalFinance":false,"exportCatalogue":true,"createGroupFromPackage":true}'::jsonb),
  ('OPERATIONS', 'pilgrims', '{"viewModule":true,"createPilgrim":true,"editPersonalDetails":true,"viewPassportAndIdentity":true,"viewDocuments":true,"uploadDocuments":true,"verifyDocuments":true,"manageVisa":false,"viewPayments":false,"recordPayments":false,"manageTravelAndRooming":true,"viewMedical":true,"editMedical":true,"manageSupportRequests":true,"viewEmergencyContact":true,"sendCommunications":true,"moveOrCancelPilgrim":true,"managePortalAccess":true,"exportPilgrims":true,"assignedGroupOnly":false}'::jsonb),
  ('OPERATIONS', 'reports', '{"viewModule":true,"viewOverview":true,"viewSales":false,"viewFinance":false,"viewGroups":true,"viewPilgrims":true,"viewSuppliers":true,"viewSaved":true,"viewCostAndMargin":false,"viewAllBranches":false,"ownGroupsOnly":false,"createCustomReports":false,"saveReports":true,"shareSavedReports":false,"scheduleReports":false,"exportCsv":true,"exportExcel":true,"exportPdf":false}'::jsonb),
  ('OPERATIONS', 'settings', '{"viewModule":true,"viewOrganisation":false,"editOrganisation":false,"viewBranches":false,"editBranches":false,"viewBranding":false,"editBranding":false,"viewOperations":true,"editOperations":true,"viewCommunications":false,"editCommunications":false,"communicationsScopedToOwnRole":false,"viewFinance":false,"editFinance":false,"viewIntegrations":false,"editIntegrations":false,"viewSecurity":false,"editSecurity":false,"viewAuditLog":false,"editData":false,"exportData":false,"importData":false,"viewDangerZone":false}'::jsonb),
  ('OPERATIONS', 'suppliers', '{"viewModule":true,"createSupplier":true,"editSupplier":true,"deactivateSupplier":true,"setReliability":true,"viewContacts":true,"viewEmergencyContactsOnly":false,"manageContacts":true,"viewCommitments":true,"createCommitment":true,"requestCommitment":true,"confirmCommitment":true,"uploadEvidence":true,"disputeCommitment":true,"viewCosts":true,"viewPayments":false,"recordPayment":false,"viewInternalNotes":true,"importExport":true,"readOnly":false,"assignedGroupOnly":false}'::jsonb),
  ('OPERATIONS', 'visa', '{"viewModule":true,"viewApplicationDetail":true,"viewVisaNumberAndFile":true,"viewFullPassportNumber":true,"createBatch":true,"manageBatch":true,"markSubmitted":true,"recordStatusCheck":true,"recordIssuedVisa":true,"verifyIssuedVisa":false,"amendIssuedVisa":false,"recordRejection":true,"requestRework":true,"assignOfficer":true,"uploadVisaEvidence":true,"sendReminders":true,"runAiAssistant":true,"exportSubmissionPack":true,"exportRiskReport":true,"viewGroupRiskBoard":true,"viewPaymentBlockersOnly":false,"readOnly":false,"assignedGroupOnly":false,"configureThresholds":false}'::jsonb),
  ('OPERATIONS', 'team', '{"viewModule":false,"viewFullDirectory":false,"inviteStaff":false,"editProfile":false,"changeRole":false,"deactivateStaff":false,"assignGroups":true,"viewWorkload":true,"viewSecurityTab":false,"manageSessionsAndPasswords":false,"exportTeamList":false,"exportAccessAudit":false,"viewOwnProfileOnly":true}'::jsonb),
  ('OPERATIONS', 'ai_agent', '{"viewModule":false,"editSettings":false,"manageKnowledgeBase":false,"viewAnalytics":false}'::jsonb),
  ('OPERATIONS', 'inbox', '{"viewModule":true,"takeControl":true,"releaseToAi":true,"sendMessage":true,"closeConversation":true,"assignConversation":true,"retryFailedJob":false}'::jsonb),
  ('VISA', 'departure_groups', '{"viewModule":true,"createGroup":false,"editGroupDetails":false,"cancelOrArchiveGroup":false,"overrideCapacityAndPrice":false,"manageFlights":true,"manageAccommodation":true,"manageTransport":true,"manageRooming":true,"unlockRoomAssignments":false,"manageReadiness":true,"manageTasks":true,"manageDocumentsAndVisa":true,"addBookings":false,"viewFinance":false,"recordPayments":false,"viewSupplierCosts":false,"viewSensitiveTravellerData":true,"sendGroupCommunications":false,"exportReports":true,"restrictedToAssignedGroups":false,"manageTravellerCustomisations":true,"approveDiscounts":false,"viewPilgrimPricing":false}'::jsonb),
  ('VISA', 'documents', '{"viewModule":true,"viewDocumentFile":true,"uploadOnBehalf":true,"verifyDocuments":true,"requestRework":true,"waiveRequirement":true,"assignReviewer":true,"sendReminders":true,"runAiScan":true,"viewAiFindings":true,"overrideAiFinding":true,"manageAgentSettings":false,"bulkActions":true,"exportChecklist":true,"exportVisaPack":true,"downloadVerifiedFiles":true,"readOnly":false,"scopedToPaymentProof":false}'::jsonb),
  ('VISA', 'finance', '{"viewModule":false,"viewReceivables":false,"viewLedger":false,"viewInvoices":false,"viewSupplierPayables":false,"viewRefunds":false,"viewReconciliation":false,"recordPayments":false,"verifyPayments":false,"reversePayments":false,"createInvoices":false,"sendInvoices":false,"voidInvoices":false,"recordSupplierPayments":false,"requestRefunds":false,"approveRefunds":false,"applyAdjustments":false,"approveAdjustments":false,"changeMilestoneDueDates":false,"assignFinanceOwner":false,"sendReminders":false,"exportFinanceReport":false,"viewPaymentStatusOnly":false,"readOnly":false}'::jsonb),
  ('VISA', 'leads', '{"viewModule":true,"createLead":false,"editLead":false,"changeStage":false,"assignLeads":false,"logContact":false,"addNote":false,"sendQuote":false,"findGroups":false,"convertToBooking":false,"mergeDuplicates":false,"deleteLead":false,"manageSourcesAndAutomation":false,"viewPipelineValue":false,"viewAnalytics":false,"viewAllOwners":true,"convertedOnly":true}'::jsonb),
  ('VISA', 'operations', '{"viewModule":true,"createTask":true,"editTask":true,"reassignTask":false,"bulkUpdateTasks":false,"completeTask":true,"viewSupplierBoard":true,"requestSupplier":true,"confirmSupplier":false,"addSupplierBooking":false,"manageFlights":false,"manageAccommodation":false,"manageRooming":false,"manageTransport":false,"assignGuide":false,"generateRunSheet":false,"exportManifest":false,"viewReadinessMatrix":true,"viewSupplierCosts":false,"viewFinanceBlockers":false,"viewPilgrimContactDetails":true,"exportOperationsReport":false,"readOnly":false,"assignedGroupOnly":false}'::jsonb),
  ('VISA', 'packages', '{"viewModule":true,"createPackage":false,"editPackage":false,"editPricing":false,"publishPackage":false,"duplicatePackage":false,"archiveOrRestorePackage":false,"deletePackage":false,"toggleFeatured":false,"viewInternalFinance":false,"exportCatalogue":true,"createGroupFromPackage":false}'::jsonb),
  ('VISA', 'pilgrims', '{"viewModule":true,"createPilgrim":false,"editPersonalDetails":true,"viewPassportAndIdentity":true,"viewDocuments":true,"uploadDocuments":true,"verifyDocuments":true,"manageVisa":true,"viewPayments":false,"recordPayments":false,"manageTravelAndRooming":false,"viewMedical":false,"editMedical":false,"manageSupportRequests":false,"viewEmergencyContact":true,"sendCommunications":true,"moveOrCancelPilgrim":false,"managePortalAccess":false,"exportPilgrims":true,"assignedGroupOnly":false}'::jsonb),
  ('VISA', 'reports', '{"viewModule":true,"viewOverview":false,"viewSales":false,"viewFinance":false,"viewGroups":false,"viewPilgrims":true,"viewSuppliers":false,"viewSaved":true,"viewCostAndMargin":false,"viewAllBranches":false,"ownGroupsOnly":false,"createCustomReports":false,"saveReports":false,"shareSavedReports":false,"scheduleReports":false,"exportCsv":true,"exportExcel":false,"exportPdf":false}'::jsonb),
  ('VISA', 'settings', '{"viewModule":true,"viewOrganisation":false,"editOrganisation":false,"viewBranches":false,"editBranches":false,"viewBranding":false,"editBranding":false,"viewOperations":false,"editOperations":false,"viewCommunications":true,"editCommunications":true,"communicationsScopedToOwnRole":true,"viewFinance":false,"editFinance":false,"viewIntegrations":false,"editIntegrations":false,"viewSecurity":false,"editSecurity":false,"viewAuditLog":false,"editData":false,"exportData":false,"importData":false,"viewDangerZone":false}'::jsonb),
  ('VISA', 'suppliers', '{"viewModule":false,"createSupplier":false,"editSupplier":false,"deactivateSupplier":false,"setReliability":false,"viewContacts":false,"viewEmergencyContactsOnly":false,"manageContacts":false,"viewCommitments":false,"createCommitment":false,"requestCommitment":false,"confirmCommitment":false,"uploadEvidence":false,"disputeCommitment":false,"viewCosts":false,"viewPayments":false,"recordPayment":false,"viewInternalNotes":false,"importExport":false,"readOnly":false,"assignedGroupOnly":false}'::jsonb),
  ('VISA', 'visa', '{"viewModule":true,"viewApplicationDetail":true,"viewVisaNumberAndFile":true,"viewFullPassportNumber":true,"createBatch":true,"manageBatch":true,"markSubmitted":true,"recordStatusCheck":true,"recordIssuedVisa":true,"verifyIssuedVisa":true,"amendIssuedVisa":true,"recordRejection":true,"requestRework":true,"assignOfficer":true,"uploadVisaEvidence":true,"sendReminders":true,"runAiAssistant":true,"exportSubmissionPack":true,"exportRiskReport":true,"viewGroupRiskBoard":true,"viewPaymentBlockersOnly":false,"readOnly":false,"assignedGroupOnly":false,"configureThresholds":false}'::jsonb),
  ('VISA', 'team', '{"viewModule":false,"viewFullDirectory":false,"inviteStaff":false,"editProfile":false,"changeRole":false,"deactivateStaff":false,"assignGroups":false,"viewWorkload":false,"viewSecurityTab":false,"manageSessionsAndPasswords":false,"exportTeamList":false,"exportAccessAudit":false,"viewOwnProfileOnly":true}'::jsonb),
  ('VISA', 'ai_agent', '{"viewModule":false,"editSettings":false,"manageKnowledgeBase":false,"viewAnalytics":false}'::jsonb),
  ('VISA', 'inbox', '{"viewModule":true,"takeControl":false,"releaseToAi":false,"sendMessage":false,"closeConversation":false,"assignConversation":false,"retryFailedJob":false}'::jsonb),
  ('GUIDE', 'departure_groups', '{"viewModule":true,"createGroup":false,"editGroupDetails":false,"cancelOrArchiveGroup":false,"overrideCapacityAndPrice":false,"manageFlights":false,"manageAccommodation":false,"manageTransport":false,"manageRooming":false,"unlockRoomAssignments":false,"manageReadiness":false,"manageTasks":true,"manageDocumentsAndVisa":false,"addBookings":false,"viewFinance":false,"recordPayments":false,"viewSupplierCosts":false,"viewSensitiveTravellerData":false,"sendGroupCommunications":false,"exportReports":false,"restrictedToAssignedGroups":true,"manageTravellerCustomisations":false,"approveDiscounts":false,"viewPilgrimPricing":false}'::jsonb),
  ('GUIDE', 'documents', '{"viewModule":false,"viewDocumentFile":false,"uploadOnBehalf":false,"verifyDocuments":false,"requestRework":false,"waiveRequirement":false,"assignReviewer":false,"sendReminders":false,"runAiScan":false,"viewAiFindings":false,"overrideAiFinding":false,"manageAgentSettings":false,"bulkActions":false,"exportChecklist":false,"exportVisaPack":false,"downloadVerifiedFiles":false,"readOnly":false,"scopedToPaymentProof":false}'::jsonb),
  ('GUIDE', 'finance', '{"viewModule":false,"viewReceivables":false,"viewLedger":false,"viewInvoices":false,"viewSupplierPayables":false,"viewRefunds":false,"viewReconciliation":false,"recordPayments":false,"verifyPayments":false,"reversePayments":false,"createInvoices":false,"sendInvoices":false,"voidInvoices":false,"recordSupplierPayments":false,"requestRefunds":false,"approveRefunds":false,"applyAdjustments":false,"approveAdjustments":false,"changeMilestoneDueDates":false,"assignFinanceOwner":false,"sendReminders":false,"exportFinanceReport":false,"viewPaymentStatusOnly":false,"readOnly":false}'::jsonb),
  ('GUIDE', 'leads', '{"viewModule":false,"createLead":false,"editLead":false,"changeStage":false,"assignLeads":false,"logContact":false,"addNote":false,"sendQuote":false,"findGroups":false,"convertToBooking":false,"mergeDuplicates":false,"deleteLead":false,"manageSourcesAndAutomation":false,"viewPipelineValue":false,"viewAnalytics":false,"viewAllOwners":false,"convertedOnly":false}'::jsonb),
  ('GUIDE', 'operations', '{"viewModule":true,"createTask":false,"editTask":false,"reassignTask":false,"bulkUpdateTasks":false,"completeTask":true,"viewSupplierBoard":false,"requestSupplier":false,"confirmSupplier":false,"addSupplierBooking":false,"manageFlights":false,"manageAccommodation":false,"manageRooming":false,"manageTransport":false,"assignGuide":false,"generateRunSheet":true,"exportManifest":true,"viewReadinessMatrix":false,"viewSupplierCosts":false,"viewFinanceBlockers":false,"viewPilgrimContactDetails":true,"exportOperationsReport":false,"readOnly":false,"assignedGroupOnly":true}'::jsonb),
  ('GUIDE', 'packages', '{"viewModule":false,"createPackage":false,"editPackage":false,"editPricing":false,"publishPackage":false,"duplicatePackage":false,"archiveOrRestorePackage":false,"deletePackage":false,"toggleFeatured":false,"viewInternalFinance":false,"exportCatalogue":false,"createGroupFromPackage":false}'::jsonb),
  ('GUIDE', 'pilgrims', '{"viewModule":true,"createPilgrim":false,"editPersonalDetails":false,"viewPassportAndIdentity":false,"viewDocuments":false,"uploadDocuments":false,"verifyDocuments":false,"manageVisa":false,"viewPayments":false,"recordPayments":false,"manageTravelAndRooming":false,"viewMedical":true,"editMedical":false,"manageSupportRequests":true,"viewEmergencyContact":true,"sendCommunications":true,"moveOrCancelPilgrim":false,"managePortalAccess":false,"exportPilgrims":false,"assignedGroupOnly":true}'::jsonb),
  ('GUIDE', 'reports', '{"viewModule":true,"viewOverview":false,"viewSales":false,"viewFinance":false,"viewGroups":true,"viewPilgrims":true,"viewSuppliers":false,"viewSaved":false,"viewCostAndMargin":false,"viewAllBranches":false,"ownGroupsOnly":true,"createCustomReports":false,"saveReports":false,"shareSavedReports":false,"scheduleReports":false,"exportCsv":false,"exportExcel":false,"exportPdf":true}'::jsonb),
  ('GUIDE', 'settings', '{"viewModule":false,"viewOrganisation":false,"editOrganisation":false,"viewBranches":false,"editBranches":false,"viewBranding":false,"editBranding":false,"viewOperations":false,"editOperations":false,"viewCommunications":false,"editCommunications":false,"communicationsScopedToOwnRole":false,"viewFinance":false,"editFinance":false,"viewIntegrations":false,"editIntegrations":false,"viewSecurity":false,"editSecurity":false,"viewAuditLog":false,"editData":false,"exportData":false,"importData":false,"viewDangerZone":false}'::jsonb),
  ('GUIDE', 'suppliers', '{"viewModule":true,"createSupplier":false,"editSupplier":false,"deactivateSupplier":false,"setReliability":false,"viewContacts":false,"viewEmergencyContactsOnly":true,"manageContacts":false,"viewCommitments":true,"createCommitment":false,"requestCommitment":false,"confirmCommitment":false,"uploadEvidence":false,"disputeCommitment":false,"viewCosts":false,"viewPayments":false,"recordPayment":false,"viewInternalNotes":false,"importExport":false,"readOnly":false,"assignedGroupOnly":true}'::jsonb),
  ('GUIDE', 'visa', '{"viewModule":true,"viewApplicationDetail":false,"viewVisaNumberAndFile":false,"viewFullPassportNumber":false,"createBatch":false,"manageBatch":false,"markSubmitted":false,"recordStatusCheck":false,"recordIssuedVisa":false,"verifyIssuedVisa":false,"amendIssuedVisa":false,"recordRejection":false,"requestRework":false,"assignOfficer":false,"uploadVisaEvidence":false,"sendReminders":false,"runAiAssistant":false,"exportSubmissionPack":false,"exportRiskReport":false,"viewGroupRiskBoard":true,"viewPaymentBlockersOnly":false,"readOnly":true,"assignedGroupOnly":true,"configureThresholds":false}'::jsonb),
  ('GUIDE', 'team', '{"viewModule":false,"viewFullDirectory":false,"inviteStaff":false,"editProfile":false,"changeRole":false,"deactivateStaff":false,"assignGroups":false,"viewWorkload":false,"viewSecurityTab":false,"manageSessionsAndPasswords":false,"exportTeamList":false,"exportAccessAudit":false,"viewOwnProfileOnly":true}'::jsonb),
  ('GUIDE', 'ai_agent', '{"viewModule":false,"editSettings":false,"manageKnowledgeBase":false,"viewAnalytics":false}'::jsonb),
  ('GUIDE', 'inbox', '{"viewModule":false,"takeControl":false,"releaseToAi":false,"sendMessage":false,"closeConversation":false,"assignConversation":false,"retryFailedJob":false}'::jsonb)
) as v(base_role, module, capabilities) on v.base_role = r.base_role
where r.is_system = true
on conflict (role_id, module) do nothing;
